ifndef::snippets[]
:snippets: ./build/generated-snippets
endif::[]
ifndef::docsdir[]
:docsdir: ./src/docs/asciidoc
endif::[]

= Debug Web Server API Docs
:toc: left
:toclevels: 3
:sectlinks:

//[[resources-users]]
== Security
=== 개요
Debug Web Server는 JWT를 통한 인증 방식을 사용합니다.

이 서버에서는 header를 통한 access token, cookie를 통한 refresh token 즉 총 두개의 토큰으로 인증을 진행합니다.

access token은 서버를 통해 유저의 정보를 가져올 수 있으며 refresh token은 access token이 만료 될 경우 다시 발급하는 용도로 사용합니다.

따라서 인증 할 때 access token만 header를 통해 서버에 보내면 됩니다.

아래에 토큰 별 만료 시간을 표 형식으로 나타냈습니다.

|===

|Token|Expired Time(ms)|Expired Time(minute)

|`+Access Token+`
|`+1800000+`
|`+30+`

|`+Refresh Token`
|`+604800000+`
|`+10080+`

|===

access token은 header를 통해 서버와 통신하기 때문에 취약점이 존재합니다.

따라서 만료 시간을 30분으로 설정했으며 페이지를 리다이렉션 할 때마다 refresh token을 이용해 재발급 하는 것을 권장합니다.

refresh token은 7일의 만료 시간을 가지며 httpOnly를 설정함으로써 access token보다 보안성이 좀 더 높습니다.

실제로 access token을 발급하기 위한 토큰이므로 필요할 때만 서버와 통신하는 것을 권장합니다.

추가로 OAuth2로 외부 인증 api를 통해 더 쉽게 로그인 또는 회원가입을 시도할 수 있습니다.

== Users
=== 유저 정보 요청
현재 인증 된(header에 정상적인 access token이 존재)의 유저 정보를 불러옵니다.

operation::user/success-get-my-user[snippets='http-request,http-response,request-headers,response-fields']

header에 토큰이 없는 경우 다음과 같은 오류가 반환됩니다.

=== 다른 유저 존재 유무
url parameter로 userId를 받아서 db에 존재하는지 확인합니다.

response data가 없기 때문에 회원가입을 할 때 id가 존재 유무 판단 용도로 사용하세요.

operation::user/user-exists[snippets='http-request,path-parameters']

==== 유저가 존재 할 때
operation::user/user-exists[snippets='http-response']

==== 유저가 존재 하지 않을 때
operation::user/user-does-not-exist[snippets='http-response']

[#_유저_회원_가입]
=== 유저 회원 가입
유저의 회원가입입니다.

operation::user/success-sign-up[snippets='http-request,http-response,request-fields']

==== 실패
아래 사항은 서버가 요청을 거부한 경우입니다.

===== 1. request field에서 userId가 이미 서버에 존재하는 경우
클라이언트에서 먼저 link:#_다른_유저_존재_유무[1차 검증]을 해주는걸 추천드립니다.

만일의 상황에 대비해서 서버에서 2차 검증이 실패하도록 구현했습니다.

operation::user/failure-sign-up-when-user-id-already-in-use[snippets='http-response']

===== 2. request로 받은 패스워드 두개가 서로 다를 때
이것도 마찬가지로 1차로 클라이언트 자체 검증을 하는걸 추천드립니다.

operation::user/failure-sign-up-when-invalid-password[snippets='http-response']

[#_oauth2_회원가입]
=== OAuth2 회원가입
OAuth2로 생성된 유저 튜플은 role이 "ROLE_GUEST"이기 때문에 권한이 로그인 안된 유저와 동급입니다.

따라서 필수로 회원가입을 마쳐야 됩니다.

기본적인 로직은 link:#_유저_회원_가입[유저 회원 가입]과 동일합니다.

operation::user/success-change-unconfirmed[snippets='http-request,http-response,request-fields']

==== 실패
아래 사항은 서버가 요청을 거부한 경우입니다.

===== 1. request field에서 userId가 이미 서버에 존재하는 경우
link:#_1_request_field에서_userid가_이미_서버에_존재하는_경우[회원가입 설명과 동일]

operation::user/failure-change-unconfirmed-when-user-id-already-in-use[snippets='http-response']

===== 2. request로 받은 패스워드 두개가 서로 다를 때
link:#_2_request로_받은_패스워드_두개가_서로_다를_때[회원가입 설명과 동일]

operation::user/failure-change-unconfirmed-when-invalid-password[snippets='http-response']

== Auth
[#_로그인]
=== 로그인
두가지 인증 방법 중 서버에 구현된 로그인을 통한 토큰 발급입니다.

아이디와 패스워드를 db에 대조해서 로그인을 시도합니다.

성공적으로 로그인이 되면 body에 access token, cookie에 refresh token이 요청자에게 반환됩니다.

operation::auth/success-login[snippets='http-request,http-response,request-fields,response-fields']

==== 실패
아래 사항은 서버가 요청을 거부한 경우입니다.

===== userId가 db에 존재하지 않을 경우 또는 userId는 db에 존재하지만 비밀번호가 틀린경우

operation::auth/failure-login-when-not-found-user[snippets='http-response']

[#_refresh]
=== Refresh
refresh token을 이용해서 access token을 발급합니다.

header에 있는 access token이 만료됬는지 확인하고 쿠키에 있는 refresh token을 통해 재발급합니다.

refresh를 정상적으로 하려면 만료된 access token 그리고 정상적인 refresh token이 필요합니다.

한개라도 없거나 잘못된 토큰일 경우 refresh가 안됩니다.이 경우에는 <<_로그인>>을 다시 해서 토큰들을 재발급하는 것을 권장합니다.

operation::auth/success-refresh-not-update-when-refresh-token[snippets='http-request,http-response']

만약 refresh token의 만료 시간이 3일 이하라면 아래와 같이 refresh token도 재발급 되어 기존과 교체됩니다.

operation::auth/success-refresh-when-update-refresh-token[snippets='http-response'']

operation::auth/success-refresh-when-update-refresh-token[snippets='request-headers,response-fields']

==== 실패

아래 사항은 서버가 요청을 거부한 경우입니다.

===== 1. access token이 위조 또는 잘못된 경우
operation::auth/failure-refresh-when-invalid-access-token[snippets='http-response']

===== 2. access token이 만료되지 않은 경우
만료되지 않았기 때문에 재발급 할 필요가 없습니다.

operation::auth/failure-refresh-when-not-expired-access-token[snippets='http-response']

===== 3. refresh token이 위조 또는 잘못된 경우
operation::auth/failure-refresh-when-invalid-refresh-token[snippets='http-response']

== OAuth2

OAuth2를 통한 인증 방식입니다.

기존 <<_로그인>>보다 좀 더 간편하게 로그인, 회원가입을 할 수 있습니다.

단 OAuth2로 기초 회원가입을 진행하면 해당 유저의 role은 "ROLE_GUEST"이기 때문에 인증이 필요한 url에 접근 할 수 없습니다.

꼭 link:#_oauth2_회원가입[회원가입]을 마치고 role이 "ROLE_UNCONFIRMED"가 되야 인증이 필요한 url에 접근 할 수 있습니다.

아래 url을 통해 외부 api로 로그인 하여 로그인 또는 회원가입을 할 수 있습니다.

----
/oauth2/authorization/{provider}?redirect_uri={redirect_uri}
----

provider의 값에 따른 외부 api 로그인 페이지가 나옵니다.

파라미터중 redirect_uri는 인증이 성공적으로 완수되면 리다이렉트 되는 페이지 입니다.

서버에서 지정한 redirect uri만 이동 할 수 있습니다.(개발 전용으로 http://localhost:3000/oauth/redirect 이용 가능)

성공적으로 리다이렉트 되면 아래와 같습니다.

----
{redirect_uri}/oauth/redirect?token={access token}
----

url에 access token이 그리고 cookie에 refresh token이 지정된 상태로 리다이렉트 됩니다.

redirect uri 값이 없거나 서버에서 허용된 url이 아닌 경우 토큰이 발급되지 않고 오류가 발생하니 주의하세요.

=== Google
Google api를 통해서 인증합니다.

----
/oauth2/authorization/google?redirect_uri={redirect_uri}
----

== Exception Handing
본 문단은 인증이 실패한 경우, 또는 리소스에 접근할 권한이 아닌 경우에 대해 설명합니다.

=== UnAuthorized(401)

==== Access Token이 없을 경우
Access Token이 없을 경우 인증이 필요한 url에 접근할 수 없습니다.

operation::access-exception-handle/unauthorized-when-access-token-is-null[snippets='http-request,http-response']

==== Access Token이 만료 됬을 경우
이 경우에는 Access Token이 유효하지만 만료되어서 사용할 수 없습니다.

link:#_refresh[refresh]를 통해서 Access Token을 재발급 받아야 인증을 할 수 있습니다.

operation::access-exception-handle/unauthorized-when-access-token-is-expired[snippets='http-request,http-response']

==== Access Token이 위조되거나 잘못된 토큰일 경우
서버에서 Access Token을 Claim화 하기전 위조(또는 잘못)된 토큰으로 판별할 경우 입니다.

operation::access-exception-handle/unauthorized-when-access-token-is-invalid[snippets='http-request,http-response']

=== Forbidden(403)

==== 사용자 Role이 "ROLE_GUEST"일 경우
OAuth2로 로그인한 유저가 아직 회원가입을 마치지 않을 경우입니다.

이 경우 link:#_oauth2_회원가입[OAuth2 회원가입] 페이지로 리다이렉트하여 회원가입을 마쳐주세요.

operation::access-exception-handle/forbidden-when-role-guest-accesses-disallowed-url[snippets='http-request,http-response']

==== 사용자 Role이 권한이 제한된 url에 접근 할 경우

operation::access-exception-handle/forbidden-when-a-non-role-guest-authenticator-accesses-a-disallowed-url[snippets='http-request,http-response']
